const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const { loadGitEnvShareConfig, resolvePrivateKeyPath, hasExplicitConfig } = require('../dist/config');
const { syncGitHubRecipientsFromConfig } = require('../dist/utils/sshEnvEncryption');

test('reads config from package.json with age as default', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ges-package-'));

  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    'git-env-share': { mode: 'age', ageKeyPath: '~/.age/key.txt' }
  }, null, 2));

  const config = loadGitEnvShareConfig(dir);

  assert.equal(config.mode, 'age');
  assert.equal(config.ageKeyPath, '~/.age/key.txt');
});

test('prefers .git-env-share.config over package.json', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ges-config-'));

  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    'git-env-share': { mode: 'age' }
  }, null, 2));
  fs.writeFileSync(path.join(dir, '.git-env-share.config'), JSON.stringify({
    mode: 'ssh', sshKeyPath: '~/.ssh/id_ed25519'
  }, null, 2));

  const config = loadGitEnvShareConfig(dir);

  assert.equal(config.mode, 'ssh');
  assert.equal(config.sshKeyPath, '~/.ssh/id_ed25519');
});

test('resolves an existing private key from config', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ges-ssh-'));
  const keyPath = path.join(dir, '.ssh', 'id_ed25519');

  fs.mkdirSync(path.dirname(keyPath), { recursive: true });
  fs.writeFileSync(keyPath, 'PRIVATE KEY');

  const resolved = resolvePrivateKeyPath({ mode: 'ssh', sshKeyPath: keyPath }, dir);

  assert.equal(resolved, keyPath);
});

test('detects explicit repo configuration before prompting for init', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ges-explicit-'));

  assert.equal(hasExplicitConfig(dir), false);

  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    'git-env-share': { mode: 'age' }
  }, null, 2));

  assert.equal(hasExplicitConfig(dir), true);

  const secondDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ges-config-file-'));
  fs.writeFileSync(path.join(secondDir, '.git-env-share.config'), JSON.stringify({ mode: 'ssh' }, null, 2));

  assert.equal(hasExplicitConfig(secondDir), true);
});

test('rebuilds .agerecipients from githubUsernames when SSH mode is configured', async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ges-sync-'));
  const recipientsPath = path.join(dir, '.agerecipients');
  const sshPublicKey = 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIexampleuser';

  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    'git-env-share': {
      mode: 'ssh',
      githubUsernames: ['octocat']
    }
  }, null, 2));

  fs.writeFileSync(recipientsPath, '# old age key\nage1oldrecipient\n');

  const server = require('node:http').createServer((req, res) => {
    if (req.url === '/octocat.keys') {
      res.writeHead(200, { 'Content-Type': 'text/plain' });
      res.end(`${sshPublicKey}\n`);
      return;
    }

    res.writeHead(404);
    res.end('not found');
  });

  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  const { port } = server.address();

  try {
    const keys = await syncGitHubRecipientsFromConfig(dir, { baseUrl: `http://127.0.0.1:${port}` });

    assert.deepEqual(keys, [sshPublicKey]);

    const fileContents = fs.readFileSync(recipientsPath, 'utf-8');
    assert.ok(fileContents.includes(sshPublicKey));
    assert.ok(!fileContents.includes('age1oldrecipient'));
    assert.ok(fileContents.startsWith('# Auto-generated by git-env-share for SSH mode'));
  } finally {
    await new Promise((resolve, reject) => server.close((err) => err ? reject(err) : resolve()));
  }
});
