import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { loadGitEnvShareConfig, resolvePrivateKeyPath } from '../config';

export function getSshHostFromRemote(): string {
  try {
    const remoteUrl = execSync('git config --get remote.origin.url', { encoding: 'utf-8' }).trim();

    if (remoteUrl.startsWith('ssh://')) {
      const url = new URL(remoteUrl);
      return url.hostname;
    }

    const scpMatch = remoteUrl.match(/^[^@]+@([^:]+):/);
    if (scpMatch && scpMatch[1]) {
      return scpMatch[1];
    }

    return 'github.com';
  } catch {
    return 'github.com';
  }
}

export function resolveSshKeyPath(projectRoot = process.cwd()): string | null {
  const config = loadGitEnvShareConfig(projectRoot);
  const keyPath = resolvePrivateKeyPath({ ...config, mode: 'ssh' }, projectRoot);

  if (keyPath && fs.existsSync(keyPath)) {
    return keyPath;
  }

  const host = getSshHostFromRemote();

  try {
    const sshOutput = execSync(`ssh -G "${host}" 2>/dev/null`, { encoding: 'utf-8' });
    const lines = sshOutput.split('\n');

    for (const line of lines) {
      if (line.toLowerCase().startsWith('identityfile ')) {
        let rawPath = line.substring(13).trim();

        if (rawPath.startsWith('~')) {
          rawPath = path.join(os.homedir(), rawPath.slice(1));
        }

        if (fs.existsSync(rawPath)) {
          return rawPath;
        }
      }
    }
  } catch {
    // SSH command failed or missing host configuration
  }

  const defaults = [
    path.join(os.homedir(), '.ssh', 'id_ed25519'),
    path.join(os.homedir(), '.ssh', 'id_rsa'),
    path.join(os.homedir(), '.ssh', 'id_ecdsa'),
    path.join(os.homedir(), '.ssh', 'id_25519')
  ];

  return defaults.find((p) => fs.existsSync(p)) || null;
}

function getGitHubKeysUrl(username: string, baseUrl?: string): string {
  const normalizedBaseUrl = (baseUrl || 'https://github.com').replace(/\/$/, '');
  return `${normalizedBaseUrl}/${encodeURIComponent(username)}.keys`;
}

export function fetchGitHubPublicKeys(username: string, options: { baseUrl?: string } = {}): Promise<string[]> {
  const normalizedUsername = String(username || '').trim();

  if (!normalizedUsername) {
    throw new Error('GitHub username is required.');
  }

  return new Promise((resolve, reject) => {
    const url = getGitHubKeysUrl(normalizedUsername, options.baseUrl);
    const transport = url.startsWith('http://') ? require('node:http') : require('node:https');

    const request = transport.get(url, (res: any) => {
      let data = '';
      res.on('data', (chunk: Buffer | string) => {
        data += chunk;
      });
      res.on('end', () => {
        if (res.statusCode !== 200 || !data.trim()) {
          reject(new Error(`No SSH keys found for GitHub user "${normalizedUsername}".`));
          return;
        }

        const keys = data.trim().split(/\r?\n/).filter(Boolean);
        if (!keys.length) {
          reject(new Error(`No SSH keys found for GitHub user "${normalizedUsername}".`));
          return;
        }

        resolve(keys);
      });
    });

    request.on('error', (err: Error) => {
      reject(err);
    });
  });
}

export async function syncGitHubRecipientsFromConfig(projectRoot = process.cwd(), options: { baseUrl?: string } = {}): Promise<string[]> {
  const config = loadGitEnvShareConfig(projectRoot);
  const recipientsPath = path.join(projectRoot, config.recipientsFile || '.agerecipients');
  const usernames = Array.isArray(config.githubUsernames) ? config.githubUsernames : [];
  const allKeys: string[] = [];

  for (const username of usernames) {
    const keys = await fetchGitHubPublicKeys(username, options);
    for (const key of keys) {
      if (!allKeys.includes(key)) {
        allKeys.push(key);
      }
    }
  }

  const generatedContent = allKeys.length > 0
    ? `# Auto-generated by git-env-share for SSH mode\n${allKeys.join('\n')}\n`
    : '# Auto-generated by git-env-share for SSH mode\n';

  fs.writeFileSync(recipientsPath, generatedContent, { encoding: 'utf-8' });
  return allKeys;
}

export async function addGitHubUser(username: string, options: { recipientsPath?: string; baseUrl?: string } = {}): Promise<string[]> {
  const recipientsPath = options.recipientsPath || path.join(process.cwd(), '.agerecipients');
  const normalizedUsername = String(username || '').trim();

  if (!normalizedUsername) {
    throw new Error('GitHub username is required.');
  }

  try {
    const keys = await fetchGitHubPublicKeys(normalizedUsername, { baseUrl: options.baseUrl });
    const existingContent = fs.existsSync(recipientsPath) ? fs.readFileSync(recipientsPath, 'utf-8') : '';
    const appended = keys.filter((key) => !existingContent.includes(key));

    if (appended.length > 0) {
      fs.appendFileSync(recipientsPath, `\n# GitHub: ${normalizedUsername}\n${appended.join('\n')}\n`);
    }

    return appended;
  } catch (error) {
    throw error;
  }
}

const username = process.argv[2];
if (username) {
  void addGitHubUser(username);
}
